[theme]
base="dark"
primaryColor="#FFB81C"        # Amarillo Duoc (Botones y selectores)
backgroundColor="#212529"     # Gris Carb√≥n (Fondo principal, resalta emojis)
secondaryBackgroundColor="#001529" # Azul Noche (Barra lateral)
textColor="#F8F9FA"           # Blanco Hueso (Texto principal)
font="sans serif"