[theme]
base="dark"
primaryColor="#FFB81C"        # Amarillo Duoc
backgroundColor="#212529"     # Gris Carb√≥n
secondaryBackgroundColor="#001529" # Azul Noche
textColor="#F8F9FA"           # Blanco
font="sans serif"