[theme]
base="dark"
primaryColor="#FFB81C"        # Amarillo Duoc (Botones, selectores, foco)
backgroundColor="#212529"     # Gris Carb√≥n Suave (Fondo principal)
secondaryBackgroundColor="#001529" # Azul Noche Profundo (Barra lateral y bloques)
textColor="#F8F9FA"           # Blanco Hueso (Texto principal)
font="sans serif"             # Fuente base (luego la refinamos con CSS)